Changed some files to better reflect the sample
Still getting errors about
"Error: Cannot find module 'express-session'"
Probably a conflict with how I included packages in the files before and how I now have to set it up in a way that lets docker find it, since although docker can't start it, a regular command line "node app.js" still works like a charm.